name: train_data
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/win-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.43.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - datasets==2.20.0
      - decorator==5.2.1
      - deepspeed==0.14.4
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - faiss-cpu==1.12.0
      - filelock==3.20.0
      - fire==0.7.1
      - flash-attn==2.6.3
      - frozenlist==1.8.0
      - fsspec==2024.5.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.2.0
      - hjson==3.1.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - peft==0.11.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==25.3
      - platformdirs==4.5.0
      - prettytable==3.16.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==5.29.5
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pyarrow-hotfix==0.7
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentry-sdk==2.42.1
      - setproctitle==1.3.7
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - timm==1.0.21
      - tokenizers==0.22.2
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.5.0
      - wandb==0.17.7
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yarl==1.22.0
